// Self-contained HTML dashboard. No build step, no CDN — open the file and it
// works, including offline.
//
// Visual direction is a grid-operations console: a deep navy ground, a giant
// monospace readout, and a faint plot-grid texture on the hero band. Every
// number is set in mono, which both reads as instrumentation and gives tabular
// alignment for free.
//
// The three series hues were run through the data-viz validator against these
// exact surfaces and pass every check on the all-pairs list in both themes
// (worst CVD ΔE 9.8 light / 9.8 dark; worst normal-vision ΔE 24.6 / 21.6).
// Changing a hex means re-running that validator.

import { WINDOW_DEFS, rankZones } from './analyze.js';
import { dataQualityWarnings, formatDuration } from './report.js';

/**
 * @param {object} options
 * @param {boolean} options.live  served by `comed.js serve` — inject the
 *                                auto-refresh poller so an open tab keeps up
 *                                with the background polling loop
 */
export function renderHtml(analysis, { live = false } = {}) {
  if (analysis.empty) {
    return page(
      'ComEd Outage Analyzer',
      '<div class="panel empty"><p>No snapshots yet — the first poll is on its way.</p></div>',
      { live },
    );
  }

  const { latest, lastDiff, windows, overall, projection, series, peak } = analysis;
  const rankingSource = windows['3h'] ?? windows['1h'] ?? windows['30m'] ?? lastDiff;
  const ranked = rankZones(rankingSource, { limit: 8 });

  const body = [
    latest.demo ? demoBanner() : '',
    hero(latest, lastDiff, projection, series, peak),
    statTiles(windows, overall, projection),
    section(
      'Restoration',
      'How much has been fixed',
      'Gross restoration — outages that closed or shrank. Each row is a different look-back window.',
      ratesTable(analysis),
    ),
    section(
      'Trend',
      'Customers out over time',
      peak ? `Peaked at ${fmt(peak.customersOut)} on ${formatLocal(peak.t)}.` : '',
      lineChart(series),
    ),
    section(
      'Flow',
      'Fixed vs. newly out',
      'Gross customer movement per interval. Net change alone hides how much crews actually restored.',
      restoredVsAddedChart(analysis),
    ),
    section(
      'Distribution',
      'Where the outages are now',
      'Customers currently without power, by area.',
      zoneBarChart(latest.byZone.slice(0, 12)),
    ),
    rankingSource
      ? section(
          'Speed',
          'Which areas are recovering fastest',
          `Share of each area's customers restored over the last ${formatDuration(rankingSource.hours)}.`,
          zoneRankTable(ranked),
        )
      : '',
    section('Detail', 'All areas', 'The complete picture, including the small ones.', zoneTable(latest, rankingSource)),
    causesAndEtr(latest),
    qualityNotes(analysis),
    footer(latest),
  ].join('\n');

  return page(
    `${latest.demo ? 'DEMO — ' : ''}ComEd — ${fmt(latest.customersOut)} out`,
    body,
    { live },
  );
}

const demoBanner = () => `
  <div class="banner" role="status">
    <span class="banner-tag">Demo</span>
    <span><strong>Synthetic data.</strong> These numbers describe a made-up storm
    generated by <code>npm run demo</code>, not a real ComEd outage. Clear
    <code>data/</code> and run <code>npm run serve</code> for live figures.</span>
  </div>`;

// --- hero ------------------------------------------------------------------

function hero(latest, lastDiff, projection, series, peak) {
  const trend =
    !lastDiff
      ? { className: 'flat', text: 'Baseline' }
      : lastDiff.net < 0
        ? { className: 'good', text: `Falling · ${fmt(-lastDiff.net)} fewer` }
        : lastDiff.net > 0
          ? { className: 'bad', text: `Rising · ${fmt(lastDiff.net)} more` }
          : { className: 'flat', text: 'Holding steady' };

  const chip = (value, unit) => {
    if (value === null || value === undefined) return '';
    const tone = value < 0 ? 'good' : value > 0 ? 'bad' : 'flat';
    const arrow = value < 0 ? '↓' : value > 0 ? '↑' : '·';
    return `<span class="chip ${tone}"><span class="chip-arrow">${arrow}</span><span class="mono">${fmt(
      Math.abs(value),
    )}</span> ${esc(unit)}</span>`;
  };

  return `
    <header class="console-head">
      <div class="console-grid" aria-hidden="true"></div>
      <div class="console-inner">
        <div class="masthead">
          <span class="wordmark">ComEd Outage Analyzer</span>
          <span class="status-pill ${trend.className}"><span class="pulse"></span>${esc(trend.text)}</span>
        </div>

        <div class="readout">
          <div class="readout-main">
            <div class="readout-number mono">${fmt(latest.customersOut)}</div>
            <div class="readout-label">customers without power</div>
          </div>
          <div class="readout-side">
            <div class="readout-secondary mono">${fmt(latest.outages)}</div>
            <div class="readout-label">active outages</div>
          </div>
        </div>

        <div class="chips">
          ${lastDiff ? chip(lastDiff.net, 'customers') : ''}
          ${lastDiff ? chip(lastDiff.netOutages, 'outages') : ''}
          ${lastDiff ? `<span class="chip-note">since last check · ${Math.round(lastDiff.hours * 60)} min</span>` : ''}
        </div>

        <div class="console-meta">
          <span>Snapshot ${esc(formatLocal(latest.capturedAt))}</span>
          <span class="dot">·</span>
          <span id="age"></span>
          ${peak ? `<span class="dot">·</span><span>Peak ${fmt(peak.customersOut)} at ${esc(formatLocal(peak.t, true))}</span>` : ''}
        </div>
      </div>
    </header>`;
}

function statTiles(windows, overall, projection) {
  const source = windows['3h'] ?? windows['1h'] ?? windows['30m'] ?? overall;
  const tiles = [
    {
      label: 'Customers fixed / hr',
      value: source ? fmt(source.restoredPerHour) : '—',
      note: source ? `over the last ${formatDuration(source.hours)}` : 'needs more history',
      tone: 'good',
    },
    {
      label: 'Outages fixed / hr',
      value: source ? fmt(source.resolvedOutagesPerHour) : '—',
      note: source ? `${fmt(source.resolvedOutages)} closed in that window` : 'needs more history',
      tone: 'good',
    },
    {
      label: 'New customers / hr',
      value: source ? fmt(source.addedPerHour) : '—',
      note: source ? `${fmt(source.newOutages)} new outages opened` : 'customers newly affected',
      tone: 'bad',
    },
    {
      label: 'Net change / hr',
      value: source ? signed(source.netPerHour) : '—',
      note: source && source.netPerHour < 0 ? 'shrinking' : 'growing',
      tone: source && source.netPerHour < 0 ? 'good' : 'bad',
    },
    {
      label: 'Projected all-clear',
      value:
        projection.status === 'improving'
          ? formatDuration(projection.hoursToClear)
          : projection.status === 'clear'
            ? 'Clear'
            : '—',
      note:
        projection.status === 'improving'
          ? 'at the current net rate'
          : projection.status === 'not-improving'
            ? 'not improving yet'
            : 'insufficient data',
      tone: 'neutral',
    },
  ];

  return `<div class="tiles">${tiles
    .map(
      (tile) => `
      <div class="tile tone-${tile.tone}">
        <div class="tile-label">${esc(tile.label)}</div>
        <div class="tile-value mono">${esc(tile.value)}</div>
        <div class="tile-note">${esc(tile.note)}</div>
      </div>`,
    )
    .join('')}</div>`;
}

const section = (eyebrow, title, note, content) => `
  <section class="panel">
    <div class="panel-head">
      <span class="eyebrow">${esc(eyebrow)}</span>
      <h2>${esc(title)}</h2>
      ${note ? `<p class="panel-note">${esc(note)}</p>` : ''}
    </div>
    ${content}
  </section>`;

// --- tables ----------------------------------------------------------------

function ratesTable(analysis) {
  const rows = WINDOW_DEFS.map((def) => ({ label: def.label, stats: analysis.windows[def.key] }))
    .concat([{ label: 'All tracked', stats: analysis.overall }])
    .filter((row) => row.stats);

  if (rows.length === 0) return '<p class="note">Need at least two snapshots.</p>';

  const body = rows
    .map(
      ({ label, stats }) => `
    <tr>
      <td class="row-head">${esc(label)}${
        stats.coarserThanRequested
          ? ' <span class="flag" title="Measured span is longer than this label — poll more often for that resolution">*</span>'
          : ''
      }</td>
      <td class="num soft mono">${esc(formatDuration(stats.hours))}</td>
      <td class="num good mono">${fmt(stats.restored)}</td>
      <td class="num good mono">${fmt(stats.resolvedOutages)}</td>
      <td class="num bad mono">${fmt(stats.added)}</td>
      <td class="num bad mono">${fmt(stats.newOutages)}</td>
      <td class="num mono">${fmt(stats.restoredPerHour)}</td>
      <td class="num mono">${fmt(stats.resolvedOutagesPerHour)}</td>
      <td class="num mono ${stats.netPerHour < 0 ? 'good' : 'bad'}">${signed(stats.netPerHour)}</td>
    </tr>`,
    )
    .join('');

  const footnote = rows.some(({ stats }) => stats.coarserThanRequested)
    ? '<p class="note">* The measured span is longer than the label — your polling interval is coarser than that window. Poll more often to get that resolution.</p>'
    : '';

  return `
    <div class="table-scroll">
      <table>
        <thead>
          <tr>
            <th rowspan="2">Window</th><th class="num" rowspan="2">Measured</th>
            <th class="num group-good" colspan="2">Fixed</th>
            <th class="num group-bad" colspan="2">New</th>
            <th class="num" colspan="2">Per hour</th>
            <th class="num" rowspan="2">Net cust/hr</th>
          </tr>
          <tr>
            <th class="num sub">customers</th><th class="num sub">outages</th>
            <th class="num sub">customers</th><th class="num sub">outages</th>
            <th class="num sub">customers</th><th class="num sub">outages</th>
          </tr>
        </thead>
        <tbody>${body}</tbody>
      </table>
    </div>
    ${footnote}`;
}

function zoneRankTable(ranked) {
  const rows = (zones, kind) =>
    zones
      .map(
        (zone) => `
      <tr>
        <td class="row-head">${esc(zone.zone)}</td>
        <td class="num mono ${kind}">${pct(zone.restoredShare)}</td>
        <td class="num mono">${fmt(zone.restored)}</td>
        <td class="num mono">${fmt(zone.resolvedOutages)}</td>
        <td class="num mono">${fmt(zone.customersAfter)}</td>
        <td class="num mono">${fmt(zone.outagesAfter)}</td>
        <td class="num mono soft">${zone.medianRestoreHours !== null ? esc(formatDuration(zone.medianRestoreHours)) : '—'}</td>
      </tr>`,
      )
      .join('');

  const table = (title, zones, kind) =>
    zones.length === 0
      ? ''
      : `
      <h3>${esc(title)}</h3>
      <div class="table-scroll">
        <table>
          <thead><tr><th>Area</th><th class="num">% fixed</th><th class="num">Customers fixed</th><th class="num">Outages fixed</th><th class="num">Customers still out</th><th class="num">Outages still out</th><th class="num">Median fix time</th></tr></thead>
          <tbody>${rows(zones, kind)}</tbody>
        </table>
      </div>`;

  const worsening =
    ranked.worsening.length === 0
      ? ''
      : `
    <h3>Getting worse</h3>
    <div class="table-scroll">
      <table>
        <thead><tr><th>Area</th><th class="num">Net change</th><th class="num">Now out</th></tr></thead>
        <tbody>${ranked.worsening
          .map(
            (zone) => `
          <tr><td class="row-head">${esc(zone.zone)}</td><td class="num mono bad">${signed(zone.net)}</td><td class="num mono">${fmt(
            zone.customersAfter,
          )}</td></tr>`,
          )
          .join('')}</tbody>
      </table>
    </div>`;

  return `${table('Recovering fastest', ranked.fastest, 'good')}${table(
    'Slowest to recover',
    ranked.slowest,
    'bad',
  )}${worsening}`;
}

function zoneTable(latest, source) {
  const byZone = new Map((source?.byZone ?? []).map((z) => [z.zone, z]));
  const rows = latest.byZone
    .map((zone) => {
      const stats = byZone.get(zone.zone);
      return `
      <tr>
        <td class="row-head">${esc(zone.zone)}</td>
        <td class="num mono">${fmt(zone.customersOut)}</td>
        <td class="num mono">${fmt(zone.outages)}</td>
        <td class="num mono">${stats ? fmt(stats.restored) : '—'}</td>
        <td class="num mono">${stats ? fmt(stats.resolvedOutages) : '—'}</td>
        <td class="num mono">${stats && stats.restoredShare !== null ? pct(stats.restoredShare) : '—'}</td>
      </tr>`;
    })
    .join('');

  const windowLabel = source ? formatDuration(source.hours) : 'window';
  return `
    <div class="table-scroll">
      <table>
        <thead><tr><th>Area</th><th class="num">Customers out</th><th class="num">Outages</th><th class="num">Customers fixed (${esc(
          windowLabel,
        )})</th><th class="num">Outages fixed</th><th class="num">% fixed</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;
}

function causesAndEtr(latest) {
  const causes = latest.causes
    .map(
      (cause) => `
    <tr><td class="row-head">${esc(cause.cause)}</td><td class="num mono">${fmt(cause.customersOut)}</td><td class="num mono">${fmt(
      cause.outages,
    )}</td></tr>`,
    )
    .join('');

  const etr = latest.etr;
  return `
  <section class="panel">
    <div class="panel-head">
      <span class="eyebrow">Context</span>
      <h2>Causes and restoration estimates</h2>
    </div>
    <div class="two-col">
      <div>
        <h3>Top causes</h3>
        <div class="table-scroll">
          <table><thead><tr><th>Cause</th><th class="num">Customers</th><th class="num">Outages</th></tr></thead><tbody>${causes}</tbody></table>
        </div>
      </div>
      <div>
        <h3>ETR health</h3>
        <ul class="facts">
          <li><span class="fact-num mono">${fmt(etr.withEtr)}</span> outages have an estimated restoration time</li>
          <li><span class="fact-num mono">${fmt(etr.withoutEtr)}</span> have none yet</li>
          <li><span class="fact-num mono ${etr.overdue > 0 ? 'bad' : ''}">${fmt(
            etr.overdue,
          )}</span> are past their promised ETR</li>
          <li><span class="fact-num mono">${
            etr.medianLeadHours !== null ? esc(formatDuration(etr.medianLeadHours)) : '—'
          }</span> median ETR from now</li>
        </ul>
      </div>
    </div>
  </section>`;
}

function qualityNotes(analysis) {
  const warnings = dataQualityWarnings(analysis);
  if (warnings.length === 0) return '';
  return `
  <section class="panel notes">
    <div class="panel-head">
      <span class="eyebrow">Caveats</span>
      <h2>Data quality</h2>
    </div>
    <ul>${warnings.map((w) => `<li>${esc(w)}</li>`).join('')}</ul>
  </section>`;
}

const footer = (latest) => `
  <footer class="page-foot">
    <span>Data from the ComEd outage map. Headline totals are ComEd's own; the
    area breakdown is derived from mapped outage locations.</span>
    <span class="mono soft">${esc(latest.capturedAt)}</span>
  </footer>`;

// --- charts ----------------------------------------------------------------

const CHART = { width: 900, height: 300, padLeft: 66, padRight: 20, padTop: 18, padBottom: 36 };

function lineChart(series) {
  if (series.length < 2) return '<p class="note">Need at least two snapshots to draw a trend.</p>';

  const { width, height, padLeft, padRight, padTop, padBottom } = CHART;
  const plotW = width - padLeft - padRight;
  const plotH = height - padTop - padBottom;

  const times = series.map((p) => Date.parse(p.t));
  const values = series.map((p) => p.customersOut);
  const tMin = Math.min(...times);
  const tMax = Math.max(...times);
  const vMax = niceCeil(Math.max(...values, 1));

  const x = (t) => padLeft + (tMax === tMin ? plotW / 2 : ((t - tMin) / (tMax - tMin)) * plotW);
  const y = (v) => padTop + plotH - (v / vMax) * plotH;

  const points = series.map((p, i) => ({ ...p, cx: x(times[i]), cy: y(p.customersOut) }));
  const path = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.cx.toFixed(1)},${p.cy.toFixed(1)}`).join(' ');
  const area =
    `M${points[0].cx.toFixed(1)},${(padTop + plotH).toFixed(1)} ` +
    points.map((p) => `L${p.cx.toFixed(1)},${p.cy.toFixed(1)}`).join(' ') +
    ` L${points.at(-1).cx.toFixed(1)},${(padTop + plotH).toFixed(1)} Z`;

  const gridlines = yTicks(vMax)
    .map(
      (v) => `
    <line class="grid" x1="${padLeft}" x2="${width - padRight}" y1="${y(v)}" y2="${y(v)}"/>
    <text class="axis" x="${padLeft - 12}" y="${y(v) + 4}" text-anchor="end">${fmt(v)}</text>`,
    )
    .join('');

  const xLabels = pickTimeTicks(points)
    .map(
      (p) => `
    <text class="axis" x="${p.cx}" y="${height - 12}" text-anchor="middle">${esc(formatLocal(p.t, true))}</text>`,
    )
    .join('');

  const hoverTargets = points
    .map(
      (p) => `
    <rect class="hit" x="${(p.cx - plotW / points.length / 2).toFixed(1)}" y="${padTop}"
          width="${Math.max(8, plotW / points.length).toFixed(1)}" height="${plotH}"
          data-x="${p.cx.toFixed(1)}" data-y="${p.cy.toFixed(1)}"
          data-label="${esc(formatLocal(p.t))}"
          data-value="${fmt(p.customersOut)} customers out"/>`,
    )
    .join('');

  const last = points.at(-1);

  return `
  <figure class="chart" data-chart="line">
    <svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Customers without power over time">
      <defs>
        <linearGradient id="areaFade" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="var(--series-1)" stop-opacity="0.34"/>
          <stop offset="100%" stop-color="var(--series-1)" stop-opacity="0.02"/>
        </linearGradient>
      </defs>
      ${gridlines}
      <path class="area-fill" d="${area}"/>
      <path class="line-1" d="${path}"/>
      ${points.length <= 40 ? points.map((p) => `<circle class="dot-1" cx="${p.cx.toFixed(1)}" cy="${p.cy.toFixed(1)}" r="3.5"/>`).join('') : ''}
      <circle class="dot-end-halo" cx="${last.cx.toFixed(1)}" cy="${last.cy.toFixed(1)}" r="9"/>
      <circle class="dot-end" cx="${last.cx.toFixed(1)}" cy="${last.cy.toFixed(1)}" r="5"/>
      <line class="crosshair" x1="0" y1="${padTop}" x2="0" y2="${padTop + plotH}" style="opacity:0"/>
      <circle class="focus-dot" r="6" style="opacity:0"/>
      ${xLabels}
      ${hoverTargets}
    </svg>
    <div class="tooltip" hidden></div>
  </figure>`;
}

function restoredVsAddedChart(analysis) {
  const { snapshots } = analysis;
  if (snapshots.length < 2) return '<p class="note">Need at least two snapshots.</p>';

  const intervals = [];
  for (let i = 1; i < snapshots.length; i++) {
    const diff = diffFor(snapshots[i - 1], snapshots[i]);
    intervals.push({ t: snapshots[i].capturedAt, restored: diff.restored, added: diff.added });
  }

  const recent = intervals.slice(-24);
  const { width, height, padLeft, padRight, padTop, padBottom } = CHART;
  const plotW = width - padLeft - padRight;
  const plotH = height - padTop - padBottom;
  const vMax = niceCeil(Math.max(1, ...recent.flatMap((d) => [d.restored, d.added])));
  const y = (v) => padTop + plotH - (v / vMax) * plotH;

  const groupW = plotW / recent.length;
  const barW = Math.max(3, groupW / 2 - 2); // 2px surface gap between adjacent bars

  const gridlines = yTicks(vMax)
    .map(
      (v) => `
    <line class="grid" x1="${padLeft}" x2="${width - padRight}" y1="${y(v)}" y2="${y(v)}"/>
    <text class="axis" x="${padLeft - 12}" y="${y(v) + 4}" text-anchor="end">${fmt(v)}</text>`,
    )
    .join('');

  const bars = recent
    .map((d, i) => {
      const gx = padLeft + i * groupW;
      const baseline = padTop + plotH;
      return `
      ${roundedBar(
        gx + groupW / 2 - barW - 1,
        y(d.restored),
        barW,
        baseline - y(d.restored),
        'bar-restored',
        `${formatLocal(d.t)} — ${fmt(d.restored)} customers fixed`,
      )}
      ${roundedBar(
        gx + groupW / 2 + 1,
        y(d.added),
        barW,
        baseline - y(d.added),
        'bar-added',
        `${formatLocal(d.t)} — ${fmt(d.added)} customers newly out`,
      )}`;
    })
    .join('');

  const xLabels = pickIndexTicks(recent)
    .map(
      ({ item, index }) => `
    <text class="axis" x="${padLeft + index * groupW + groupW / 2}" y="${height - 12}" text-anchor="middle">${esc(
      formatLocal(item.t, true),
    )}</text>`,
    )
    .join('');

  return `
  <div class="legend">
    <span class="legend-item"><span class="swatch swatch-restored"></span>Fixed</span>
    <span class="legend-item"><span class="swatch swatch-added"></span>Newly out</span>
  </div>
  <figure class="chart" data-chart="bars">
    <svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Customers fixed versus newly out per interval">
      ${gridlines}
      ${bars}
      ${xLabels}
    </svg>
    <div class="tooltip" hidden></div>
  </figure>`;
}

function zoneBarChart(zones) {
  if (zones.length === 0) return '<p class="note">No outages mapped.</p>';

  const rowH = 32;
  const width = 900;
  const labelW = 210;
  const valueW = 96;
  const barMax = width - labelW - valueW - 16;
  const height = zones.length * rowH + 8;
  const max = Math.max(...zones.map((z) => z.customersOut), 1);

  const rows = zones
    .map((zone, i) => {
      const y = i * rowH + 6;
      const barW = Math.max(2, (zone.customersOut / max) * barMax);
      return `
      <text class="row-label" x="0" y="${y + 14}">${esc(zone.zone)}</text>
      ${roundedBar(
        labelW,
        y,
        barW,
        18,
        'bar-primary',
        `${zone.zone} — ${fmt(zone.customersOut)} customers out across ${fmt(zone.outages)} outages`,
        true,
      )}
      <text class="row-value" x="${labelW + barW + 10}" y="${y + 14}">${fmt(zone.customersOut)}</text>`;
    })
    .join('');

  return `
  <figure class="chart" data-chart="hbars">
    <svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Customers out by area">${rows}</svg>
    <div class="tooltip" hidden></div>
  </figure>`;
}

// --- svg helpers -----------------------------------------------------------

/** Bar with 4px rounded data-end, square against the baseline. */
function roundedBar(x, y, width, height, className, tooltip, horizontal = false) {
  const h = Math.max(0, height);
  const w = Math.max(0, width);
  const r = Math.min(4, horizontal ? h / 2 : w / 2, horizontal ? w : h);
  if (w <= 0 || h <= 0) return '';

  const d = horizontal
    ? `M${x},${y} H${x + w - r} Q${x + w},${y} ${x + w},${y + r} V${y + h - r} Q${x + w},${y + h} ${x + w - r},${y + h} H${x} Z`
    : `M${x},${y + h} V${y + r} Q${x},${y} ${x + r},${y} H${x + w - r} Q${x + w},${y} ${x + w},${y + r} V${y + h} Z`;

  return `<path class="${className}" d="${d}" data-tip="${esc(tooltip)}"/>`;
}

const yTicks = (max) => [0, max / 4, max / 2, (max * 3) / 4, max].map((v) => Math.round(v));

function niceCeil(value) {
  if (value <= 10) return 10;
  const magnitude = 10 ** Math.floor(Math.log10(value));
  return Math.ceil(value / (magnitude / 2)) * (magnitude / 2);
}

function pickTimeTicks(points, target = 6) {
  const step = Math.max(1, Math.ceil(points.length / target));
  return points.filter((_, i) => i % step === 0 || i === points.length - 1);
}

function pickIndexTicks(items, target = 6) {
  const step = Math.max(1, Math.ceil(items.length / target));
  return items
    .map((item, index) => ({ item, index }))
    .filter(({ index }) => index % step === 0 || index === items.length - 1);
}

/** Local, dependency-free recompute for chart bars — only the gross totals. */
function diffFor(before, after) {
  const beforeById = new Map(before.outages.map((o) => [o.id, o]));
  const afterById = new Map(after.outages.map((o) => [o.id, o]));
  let restored = 0;
  let added = 0;
  for (const [id, prior] of beforeById) {
    const current = afterById.get(id);
    if (!current) {
      restored += prior.customersAffected;
      continue;
    }
    const delta = current.customersAffected - prior.customersAffected;
    if (delta < 0) restored += -delta;
    else added += delta;
  }
  for (const [id, current] of afterById) {
    if (!beforeById.has(id)) added += current.customersAffected;
  }
  return { restored, added };
}

// --- page shell ------------------------------------------------------------

const LIVE_SCRIPT = `<script>
(function () {
  var current = null;
  function check() {
    fetch('/api.json', { cache: 'no-store' })
      .then(function (res) { return res.json(); })
      .then(function (data) {
        if (current && data.capturedAt !== current) { location.reload(); return; }
        current = data.capturedAt;
      })
      .catch(function () { /* server restarting; try again next tick */ });
  }
  check();
  setInterval(check, 20000);
  document.addEventListener('visibilitychange', function () {
    if (!document.hidden) check();
  });
})();
</script>`;

function page(title, body, { live = false } = {}) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
:root {
  color-scheme: light dark;

  --font-sans: system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  --font-mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;

  --ground:        #f7f9fc;
  --surface-1:     #ffffff;
  --surface-2:     #eaeff8;
  --surface-sunk:  #f0f4fa;
  --text-primary:  #0a0e1a;
  --text-secondary:#4a5878;
  --text-muted:    #71809f;
  --grid:          #dbe3f0;
  --border:        rgba(10, 14, 26, 0.11);
  --border-strong: rgba(10, 14, 26, 0.20);

  --series-1: #2072e0;
  --restored: #0f9c68;
  --added:    #dd5f22;

  --hero-ground: #101a30;
  --hero-text:   #eef3ff;
  --hero-muted:  #9aabd0;
  --hero-grid:   rgba(140, 175, 255, 0.13);
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --ground:        #0a0e1a;
    --surface-1:     #111828;
    --surface-2:     #162034;
    --surface-sunk:  #0d1322;
    --text-primary:  #eef3ff;
    --text-secondary:#9aabd0;
    --text-muted:    #7385ad;
    --grid:          #1e2942;
    --border:        rgba(140, 175, 255, 0.15);
    --border-strong: rgba(140, 175, 255, 0.28);

    --series-1: #3585e0;
    --restored: #12a976;
    --added:    #e56a2e;

    --hero-ground: #0d1526;
    --hero-text:   #eef3ff;
    --hero-muted:  #9aabd0;
    --hero-grid:   rgba(140, 175, 255, 0.10);
  }
}

:root[data-theme="dark"] {
  --ground:        #0a0e1a;
  --surface-1:     #111828;
  --surface-2:     #162034;
  --surface-sunk:  #0d1322;
  --text-primary:  #eef3ff;
  --text-secondary:#9aabd0;
  --text-muted:    #7385ad;
  --grid:          #1e2942;
  --border:        rgba(140, 175, 255, 0.15);
  --border-strong: rgba(140, 175, 255, 0.28);

  --series-1: #3585e0;
  --restored: #12a976;
  --added:    #e56a2e;

  --hero-ground: #0d1526;
  --hero-text:   #eef3ff;
  --hero-muted:  #9aabd0;
  --hero-grid:   rgba(140, 175, 255, 0.10);
}

* { box-sizing: border-box; }

body {
  margin: 0;
  padding: 0 20px 72px;
  background: var(--ground);
  color: var(--text-primary);
  font-family: var(--font-sans);
  font-size: 15px;
  line-height: 1.55;
  -webkit-font-smoothing: antialiased;
}

.mono { font-family: var(--font-mono); font-variant-numeric: tabular-nums; }
.soft { color: var(--text-muted); }
.good { color: var(--restored); }
.bad  { color: var(--added); }
.note { color: var(--text-secondary); font-size: 13px; margin: 10px 0 0; }

/* --- hero console --- */
.console-head {
  position: relative;
  overflow: hidden;
  background: var(--hero-ground);
  color: var(--hero-text);
  /* Full-bleed into the top edge when it leads the page; a floating band when
     the demo banner pushes it down. */
  border-radius: 18px;
  margin: 18px -20px 26px;
  padding: 30px 20px 34px;
}
.console-head:first-child {
  border-radius: 0 0 20px 20px;
  margin-top: 0;
}
.console-grid {
  position: absolute; inset: 0;
  background-image:
    linear-gradient(var(--hero-grid) 1px, transparent 1px),
    linear-gradient(90deg, var(--hero-grid) 1px, transparent 1px);
  background-size: 34px 34px;
  -webkit-mask-image: linear-gradient(180deg, rgba(0,0,0,0.85), transparent 78%);
  mask-image: linear-gradient(180deg, rgba(0,0,0,0.85), transparent 78%);
  pointer-events: none;
}
.console-inner { position: relative; max-width: 1040px; margin: 0 auto; }

.masthead { display: flex; align-items: center; justify-content: space-between; gap: 16px; flex-wrap: wrap; }
.wordmark {
  font-size: 12px; font-weight: 700; letter-spacing: 0.16em; text-transform: uppercase;
  color: var(--hero-muted);
}
.status-pill {
  display: inline-flex; align-items: center; gap: 7px;
  font-size: 12px; font-weight: 600; letter-spacing: 0.02em;
  padding: 5px 12px 5px 10px; border-radius: 999px;
  border: 1px solid var(--border-strong); background: rgba(255,255,255,0.05);
}
.status-pill .pulse { width: 7px; height: 7px; border-radius: 50%; background: currentColor; }
.status-pill.good { color: var(--restored); }
.status-pill.bad  { color: var(--added); }
.status-pill.flat { color: var(--hero-muted); }

.readout { display: flex; align-items: flex-end; gap: 44px; flex-wrap: wrap; margin: 22px 0 0; }
.readout-number {
  font-size: clamp(58px, 13vw, 108px);
  font-weight: 700; line-height: 0.92; letter-spacing: -0.045em;
  color: var(--hero-text);
  text-shadow: 0 0 46px rgba(53, 133, 224, 0.34);
}
.readout-secondary {
  font-size: clamp(30px, 6vw, 46px);
  font-weight: 700; line-height: 1; letter-spacing: -0.035em; color: var(--hero-text);
}
.readout-label {
  font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase;
  color: var(--hero-muted); margin-top: 9px;
}

.chips { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-top: 22px; }
.chip {
  display: inline-flex; align-items: center; gap: 6px;
  font-size: 13px; font-weight: 600;
  padding: 5px 12px; border-radius: 999px;
  background: rgba(255,255,255,0.06); border: 1px solid var(--border-strong);
}
.chip.good { color: var(--restored); }
.chip.bad  { color: var(--added); }
.chip.flat { color: var(--hero-muted); }
.chip-arrow { font-size: 14px; line-height: 1; }
.chip-note { font-size: 12px; color: var(--hero-muted); }

.console-meta {
  display: flex; gap: 8px; flex-wrap: wrap;
  margin-top: 20px; font-size: 12px; color: var(--hero-muted);
}
.console-meta .dot { opacity: 0.5; }

/* --- banner --- */
.banner {
  max-width: 1040px; margin: 20px auto -4px;
  display: flex; gap: 12px; align-items: flex-start;
  background: var(--surface-2); border: 1px solid var(--added);
  border-radius: 12px; padding: 13px 16px; font-size: 13px; line-height: 1.5;
}
.banner-tag {
  flex: none; font-size: 10px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase;
  background: var(--added); color: #fff; padding: 3px 8px; border-radius: 5px; margin-top: 1px;
}

/* --- tiles --- */
.tiles {
  max-width: 1040px; margin: 0 auto 30px;
  display: grid; grid-template-columns: repeat(auto-fit, minmax(178px, 1fr)); gap: 12px;
}
.tile {
  background: var(--surface-1); border: 1px solid var(--border);
  border-radius: 14px; padding: 15px 17px 17px;
}
.tile-label {
  font-size: 10px; font-weight: 700; letter-spacing: 0.13em; text-transform: uppercase;
  color: var(--text-muted);
}
.tile-value { font-size: 31px; font-weight: 700; letter-spacing: -0.03em; margin: 9px 0 3px; line-height: 1.05; }
.tone-good .tile-value { color: var(--restored); }
.tone-bad  .tile-value { color: var(--added); }
.tile-note { font-size: 12px; color: var(--text-secondary); }

/* --- panels --- */
.panel {
  max-width: 1040px; margin: 0 auto 22px;
  background: var(--surface-1); border: 1px solid var(--border);
  border-radius: 16px; padding: 22px 24px 24px;
}
.panel-head { margin-bottom: 18px; }
.eyebrow {
  display: inline-block; font-size: 10px; font-weight: 800;
  letter-spacing: 0.15em; text-transform: uppercase; color: var(--series-1);
  margin-bottom: 7px;
}
.panel h2 { font-size: 19px; margin: 0; letter-spacing: -0.02em; text-wrap: balance; }
.panel-note { margin: 7px 0 0; font-size: 13px; color: var(--text-secondary); max-width: 68ch; }
.panel h3 {
  font-size: 11px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase;
  color: var(--text-muted); margin: 24px 0 9px;
}
.panel h3:first-of-type { margin-top: 4px; }

/* --- charts --- */
.chart { margin: 0; position: relative; background: var(--surface-sunk); border-radius: 11px; padding: 10px 12px; }
.chart svg { width: 100%; height: auto; display: block; overflow: visible; }
.grid { stroke: var(--grid); stroke-width: 1; }
.axis { fill: var(--text-muted); font-size: 11px; font-family: var(--font-mono); font-variant-numeric: tabular-nums; }
.row-label { fill: var(--text-primary); font-size: 13px; font-family: var(--font-sans); }
.row-value { fill: var(--text-secondary); font-size: 12px; font-family: var(--font-mono); font-variant-numeric: tabular-nums; }
.line-1 { fill: none; stroke: var(--series-1); stroke-width: 2.5; stroke-linejoin: round; stroke-linecap: round; }
.area-fill { fill: url(#areaFade); }
.dot-1 { fill: var(--series-1); stroke: var(--surface-sunk); stroke-width: 2; }
.dot-end { fill: var(--series-1); stroke: var(--surface-sunk); stroke-width: 2.5; }
.dot-end-halo { fill: var(--series-1); opacity: 0.22; }
.bar-primary { fill: var(--series-1); }
.bar-restored { fill: var(--restored); }
.bar-added { fill: var(--added); }
.hit { fill: transparent; cursor: crosshair; }
.crosshair { stroke: var(--text-muted); stroke-width: 1; stroke-dasharray: 3 3; }
.focus-dot { fill: var(--series-1); stroke: var(--surface-sunk); stroke-width: 2.5; }

.legend { display: flex; gap: 18px; margin-bottom: 11px; font-size: 12px; font-weight: 600; color: var(--text-secondary); }
.legend-item { display: inline-flex; align-items: center; gap: 7px; }
.swatch { width: 11px; height: 11px; border-radius: 3px; display: inline-block; }
.swatch-restored { background: var(--restored); }
.swatch-added { background: var(--added); }

.tooltip {
  position: absolute; pointer-events: none; z-index: 5;
  background: var(--surface-1); color: var(--text-primary);
  border: 1px solid var(--border-strong); border-radius: 9px;
  padding: 8px 11px; font-size: 12px; line-height: 1.4;
  box-shadow: 0 8px 26px rgba(0,0,0,0.26); white-space: nowrap;
}

/* --- tables --- */
.table-scroll { overflow-x: auto; }
table { border-collapse: collapse; width: 100%; font-size: 13px; }
th, td { text-align: left; padding: 8px 11px; border-bottom: 1px solid var(--border); }
thead th {
  color: var(--text-muted); font-weight: 700; font-size: 10px;
  letter-spacing: 0.1em; text-transform: uppercase; white-space: nowrap;
}
th.sub { font-weight: 600; font-size: 10px; opacity: 0.85; }
th.group-good { color: var(--restored); }
th.group-bad { color: var(--added); }
.num { text-align: right; white-space: nowrap; }
.row-head { font-weight: 600; }
tbody tr:last-child td { border-bottom: none; }
tbody tr { transition: background 120ms ease; }
tbody tr:hover { background: var(--surface-2); }
.flag { color: var(--added); font-weight: 800; cursor: help; }

.two-col { display: grid; grid-template-columns: repeat(auto-fit, minmax(290px, 1fr)); gap: 30px; }
.facts { margin: 4px 0 0; padding: 0; list-style: none; }
.facts li {
  display: flex; align-items: baseline; gap: 10px;
  padding: 7px 0; border-bottom: 1px solid var(--border);
  font-size: 13px; color: var(--text-secondary);
}
.facts li:last-child { border-bottom: none; }
.fact-num { font-size: 17px; font-weight: 700; color: var(--text-primary); min-width: 3.2em; }

.notes ul { margin: 0; padding-left: 18px; color: var(--text-secondary); font-size: 13px; }
.notes li { margin-bottom: 7px; }
.notes li:last-child { margin-bottom: 0; }

.empty { text-align: center; color: var(--text-secondary); padding: 44px 20px; }

.page-foot {
  max-width: 1040px; margin: 32px auto 0;
  display: flex; justify-content: space-between; gap: 16px; flex-wrap: wrap;
  font-size: 12px; color: var(--text-muted); line-height: 1.5;
}

code {
  background: var(--surface-sunk); border: 1px solid var(--border);
  padding: 1px 5px; border-radius: 5px;
  font-family: var(--font-mono); font-size: 12px;
  white-space: nowrap;
}

:focus-visible { outline: 2px solid var(--series-1); outline-offset: 2px; border-radius: 4px; }

@media (prefers-reduced-motion: reduce) {
  * { transition: none !important; animation: none !important; }
}

@media (max-width: 640px) {
  .readout { gap: 26px; }
  .panel { padding: 18px 15px 20px; border-radius: 13px; }
  .console-head { padding: 24px 18px 28px; }
}
</style>
</head>
<body>
${body}
<script>
(function () {
  document.querySelectorAll('[data-chart="line"]').forEach(function (figure) {
    var tooltip = figure.querySelector('.tooltip');
    var crosshair = figure.querySelector('.crosshair');
    var focusDot = figure.querySelector('.focus-dot');
    figure.querySelectorAll('.hit').forEach(function (hit) {
      hit.addEventListener('mouseenter', function () {
        var x = hit.getAttribute('data-x');
        var y = hit.getAttribute('data-y');
        crosshair.setAttribute('x1', x); crosshair.setAttribute('x2', x);
        crosshair.style.opacity = 1;
        focusDot.setAttribute('cx', x); focusDot.setAttribute('cy', y);
        focusDot.style.opacity = 1;
        tooltip.innerHTML = '<strong>' + hit.getAttribute('data-value') + '</strong><br>' + hit.getAttribute('data-label');
        tooltip.hidden = false;
      });
      hit.addEventListener('mousemove', function (event) { place(figure, tooltip, event); });
    });
    figure.addEventListener('mouseleave', function () {
      tooltip.hidden = true;
      crosshair.style.opacity = 0;
      focusDot.style.opacity = 0;
    });
  });

  document.querySelectorAll('[data-chart="bars"], [data-chart="hbars"]').forEach(function (figure) {
    var tooltip = figure.querySelector('.tooltip');
    figure.querySelectorAll('[data-tip]').forEach(function (mark) {
      mark.addEventListener('mouseenter', function () {
        tooltip.textContent = mark.getAttribute('data-tip');
        tooltip.hidden = false;
      });
      mark.addEventListener('mousemove', function (event) { place(figure, tooltip, event); });
    });
    figure.addEventListener('mouseleave', function () { tooltip.hidden = true; });
  });

  function place(figure, tooltip, event) {
    var box = figure.getBoundingClientRect();
    var x = event.clientX - box.left + 14;
    var y = event.clientY - box.top - 10;
    if (x + tooltip.offsetWidth > box.width) x = event.clientX - box.left - tooltip.offsetWidth - 14;
    tooltip.style.left = Math.max(0, x) + 'px';
    tooltip.style.top = Math.max(0, y) + 'px';
  }

  var ageEl = document.getElementById('age');
  if (ageEl) {
    var start = Date.now();
    function tick() {
      var mins = Math.round((Date.now() - start) / 60000);
      ageEl.textContent = mins < 1 ? 'just loaded' : 'loaded ' + mins + ' min ago';
    }
    tick();
    setInterval(tick, 15000);
  }
})();
</script>
${live ? LIVE_SCRIPT : ''}
</body>
</html>`;
}

// --- formatting ------------------------------------------------------------

const esc = (value) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const fmt = (n) =>
  n === null || n === undefined || !Number.isFinite(n) ? '—' : Math.round(n).toLocaleString('en-US');

const signed = (n) => (n === null || !Number.isFinite(n) ? '—' : n > 0 ? `+${fmt(n)}` : fmt(n));
const pct = (n) => (n === null || !Number.isFinite(n) ? '—' : `${(n * 100).toFixed(0)}%`);

function formatLocal(iso, timeOnly = false) {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return String(iso);
  return timeOnly
    ? date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
    : date.toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
}
